<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-5AH013U" failures="1" tests="1" name="Default test" time="9.427" errors="0" timestamp="2024-09-24T23:31:09 EEST">
  <testcase classname="test_loginPage.LoginPageCompTest" name="TestUserLoginWithJavaFaker" time="0.518">
    <failure type="java.lang.AssertionError" message="Expected: &amp;apos;https://www.saucedemo.com/&amp;apos; to be found, but actually: &amp;apos;https://www.saucedemo.com/&amp;apos; is found.">
      <![CDATA[java.lang.AssertionError: Expected: 'https://www.saucedemo.com/' to be found, but actually: 'https://www.saucedemo.com/' is found.
at Utility.TestingMethod.CheckIfActualEqualsExpected(TestingMethod.java:32)
at comp_login.LoginPageComp.CheckUserLoginWithJavaFaker(LoginPageComp.java:154)
at test_loginPage.LoginPageCompTest.TestUserLoginWithJavaFaker(LoginPageCompTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TestUserLoginWithJavaFaker -->
  <testcase classname="test_loginPage.LoginPageCompTest" name="CheckUserLoginWithValidData" time="0.0">
    <ignored/>
  </testcase> <!-- CheckUserLoginWithValidData -->
  <testcase classname="test_loginPage.LoginPageCompTest" name="CheckLoginDataWithExcelFile" time="0.0">
    <ignored/>
  </testcase> <!-- CheckLoginDataWithExcelFile -->
  <testcase classname="test_loginPage.LoginPageCompTest" name="CheckLoginPageOpened" time="0.0">
    <ignored/>
  </testcase> <!-- CheckLoginPageOpened -->
  <testcase classname="test_loginPage.LoginPageCompTest" name="CheckInvalidData" time="0.0">
    <ignored/>
  </testcase> <!-- CheckInvalidData -->
  <testcase classname="test_loginPage.LoginPageCompTest" name="TestUserLoginWithValidDataByJson" time="0.0">
    <ignored/>
  </testcase> <!-- TestUserLoginWithValidDataByJson -->
  <testcase classname="test_loginPage.LoginPageCompTest" name="CheckLoginWithConfig" time="0.0">
    <ignored/>
  </testcase> <!-- CheckLoginWithConfig -->
</testsuite> <!-- Default test -->
